"""teste8

Revision ID: 277a267a4acb
Revises: d81d631679e3
Create Date: 2023-07-14 10:49:27.166465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277a267a4acb'
down_revision = 'd81d631679e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_artigospublicados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('titulopesquisa', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['tbl_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('artigospublicados')
    op.drop_table('usuarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('usuarios_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='usuarios_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('artigospublicados',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulopesquisa', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='artigospublicados_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='artigospublicados_pkey')
    )
    op.drop_table('tbl_artigospublicados')
    op.drop_table('tbl_usuarios')
    # ### end Alembic commands ###
