"""teste5

Revision ID: 358c0253ab2b
Revises: add787788b4a
Create Date: 2023-07-14 10:44:50.586518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358c0253ab2b'
down_revision = 'add787788b4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
