"""teste3

Revision ID: 43ae2d2433fa
Revises: e9eb05882859
Create Date: 2023-07-14 10:31:36.453769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ae2d2433fa'
down_revision = 'e9eb05882859'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
