"""teste9

Revision ID: 63d6c63a3e80
Revises: 277a267a4acb
Create Date: 2023-07-14 10:57:33.123788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d6c63a3e80'
down_revision = '277a267a4acb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
