"""teste4

Revision ID: add787788b4a
Revises: 43ae2d2433fa
Create Date: 2023-07-14 10:37:15.960833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add787788b4a'
down_revision = '43ae2d2433fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artigospublicados', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artigospublicados', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artigospublicados', type_='foreignkey')
    op.drop_column('artigospublicados', 'usuario_id')
    # ### end Alembic commands ###
