"""teste6

Revision ID: d81d631679e3
Revises: 358c0253ab2b
Create Date: 2023-07-14 10:47:21.933909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81d631679e3'
down_revision = '358c0253ab2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
