"""teste2

Revision ID: e9eb05882859
Revises: e84f40ca6c9c
Create Date: 2023-07-14 10:19:53.792006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9eb05882859'
down_revision = 'e84f40ca6c9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artigospublicados_usuario_id_fkey', 'artigospublicados', type_='foreignkey')
    op.drop_column('artigospublicados', 'usuario_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artigospublicados', sa.Column('usuario_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('artigospublicados_usuario_id_fkey', 'artigospublicados', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###
